// Auto-extracted grammar content data (pure data, no logic).
export const TAG_ID = {
  1: "a / an / the / Ø (tanpa artikel)",
  2: "Kata benda terhitung, tak terhitung & kuantifier",
  3: "Preposisi pasangan & frasanya",
  4: "Perbandingan & superlatif",
  5: "Kesesuaian subjek–kata kerja",
  6: "Simple, continuous, perfect (lampau)",
  7: "Simple, continuous, perfect (kini)",
  8: "will, going to & bentuk perfect",
  9: "be + V3 di semua tense",
  10: "Tipe 1, 2, 3 & campuran",
  11: "Kemampuan, kemungkinan, keharusan",
  12: "who, which, that, whose…",
  13: "Klausa & kata hubung",
};

export const LEARN_ID = {
  1: [
    "Pakai a/an untuk benda tunggal terhitung yang belum spesifik atau baru pertama kali disebut.",
    "Pakai the untuk sesuatu yang spesifik, sudah disebut, satu-satunya, atau bentuk superlatif.",
    "Tanpa artikel (Ø) untuk kata benda jamak/tak terhitung bermakna umum dan kebanyakan nama diri.",
  ],
  2: [
    "Kata benda tak terhitung (information, advice, research…) tidak punya bentuk jamak, tidak memakai a/an, dan kata kerjanya tunggal; ukur dengan “a piece of…”.",
    "some untuk kalimat positif, tawaran, dan permintaan; any untuk kalimat negatif dan pertanyaan.",
    "many/a few untuk terhitung, much/a little untuk tak terhitung; a lot of bisa keduanya. few/little = hampir tidak ada; a few/a little = ada beberapa, cukup.",
  ],
  3: [
    "Banyak kata kerja punya preposisi pasangan tetap: depend on, wait for, deal with — hafalkan sebagai satu paket.",
    "Kata sifat juga punya pasangan: interested in, responsible for, capable of, satisfied with.",
    "Kata benda pun begitu: increase in, impact on, demand for, reason for.",
    "Kalau ragu, cek kamus kolokasi untuk melihat preposisi yang lazim mengikuti sebuah kata.",
  ],
  4: [
    "Komparatif: kata sifat pendek + -er, kata sifat panjang pakai more, lalu “than”; jangan digandakan (✗ more cheaper).",
    "Superlatif: the + -est / the most untuk tiga hal atau lebih; “the” hilang setelah kata milik (our best package).",
    "Perkuat dengan slightly/far/significantly + komparatif atau by far + superlatif; pola “the more…, the more…” menunjukkan perubahan.",
  ],
  5: [
    "Subjek tunggal → kata kerja tunggal; subjek jamak → jamak. Dengan or/nor, kata kerja mengikuti subjek terdekat.",
    "everyone/each/every → tunggal; few/many/several → jamak; some/all/none mengikuti kata benda setelahnya. “The number of” tunggal, “a number of” jamak.",
    "There is/are mengikuti subjek di belakangnya; judul, negara, jumlah uang, dan mata pelajaran seperti mathematics dihitung tunggal.",
  ],
  6: [
    "Past simple untuk aksi selesai dan urutan kejadian di masa lampau.",
    "used to/would untuk kebiasaan lampau; hanya used to yang bisa dipakai untuk keadaan (state).",
    "Past continuous untuk aksi yang sedang berlangsung di satu titik lampau, sering “dipotong” oleh past simple.",
    "Past perfect (had + V3) untuk kejadian yang lebih dulu dari kejadian lampau lain.",
    "Past perfect continuous menekankan durasi sampai satu titik di masa lampau.",
  ],
  7: [
    "Present simple untuk rutinitas, fakta umum, dan jadwal.",
    "Present continuous untuk situasi sementara, yang sedang terjadi, dan tren; kata kerja keadaan (know, want…) biasanya tidak memakai bentuk ini.",
    "Present perfect menghubungkan lampau dengan sekarang (for/since, ever, yet); kalau waktunya disebut jelas, pakai past simple.",
    "Present perfect continuous menekankan durasi/aktivitasnya; bentuk simple menekankan hasil atau jumlah.",
  ],
  8: [
    "will untuk keputusan spontan, janji, dan prediksi berdasar opini.",
    "going to untuk rencana yang sudah ada dan prediksi dari bukti; present continuous untuk janji temu pasti, present simple untuk jadwal.",
    "Future continuous (will be + V-ing) untuk aksi yang sedang berlangsung di satu waktu di masa depan.",
    "Future perfect (will have + V3) untuk yang selesai sebelum satu titik di masa depan (by / by the time).",
    "Future perfect continuous untuk durasi sampai satu titik di masa depan.",
  ],
  9: [
    "Bentuk pasif = be + V3, dan “be”-nya berubah mengikuti tense (is discussed, was discussed, has been discussed…).",
    "Pakai pasif saat objek lebih penting daripada pelaku, pelakunya tak diketahui, atau untuk nada akademik yang formal.",
  ],
  10: [
    "Tipe 1 (nyata & mungkin): If + present, will.",
    "Tipe 2 (tidak nyata sekarang): If + past simple, would; dengan “be” pakai were.",
    "Tipe 3 (tidak nyata di masa lampau): If + past perfect, would have + V3.",
    "Campuran: syarat lampau, hasil sekarang — If + past perfect, would + kata kerja dasar.",
  ],
  11: [
    "can/could untuk kemampuan; be able to saat “can” tidak bisa dipakai; may/might/could untuk kemungkinan yang tidak pasti.",
    "could/might have + V3 = kemungkinan lampau; must have = yakin terjadi; can’t have = yakin tidak terjadi.",
    "must/have to untuk keharusan (lampau: had to); should have + V3 untuk penyesalan; had better memberi peringatan.",
    "Modals mengatur kekuatan opini: “could lead to” terdengar lebih berimbang daripada “will lead to”.",
  ],
  12: [
    "Klausa defining memberi info penting, tanpa koma; who/which/that bisa dihilangkan kalau berperan sebagai objek.",
    "Klausa non-defining memberi info tambahan di antara koma; jangan pakai “that” dan jangan hilangkan kata gantinya.",
    "whose = kepemilikan, where = tempat, when = waktu.",
  ],
  13: [
    "Klausa independen bisa berdiri sendiri; klausa dependen tidak. Hindari comma splice dan kalimat fragmen.",
    "Sebab-akibat: because/since/as + klausa; because of/due to + kata benda; so menunjukkan akibat.",
    "Kontras: although/even though + klausa; despite/in spite of + kata benda.",
    "Tujuan: so that + klausa, in order to + kata kerja; klausa waktu: when, while, before, after, until, as soon as.",
    "Untuk band 7 tidak perlu kalimat super panjang — variasi yang akurat lebih penting.",
  ],
};

export const EX_ID = {
  "1-0": "“The number of…” merujuk jumlah yang spesifik, jadi pakai “the” (dan kata kerja tunggal).",
  "1-1": "Baru pertama kali disebut, satu dari banyak lini produk → a.",
  "1-2": "Kata benda jamak yang bermakna umum tidak memakai artikel.",
  "1-3": "Superlatif selalu memakai “the”: the most popular.",
  "1-4": "Satu kenaikan yang belum spesifik, baru diperkenalkan → a.",
  "1-5": "Satu periode (tidak ditentukan yang mana) sepanjang itu → a three-year period.",
  "1-6": "“A significant decrease” baru pertama kali disebut → a.",
  "1-7": "Kebanyakan nama kota dan negara adalah nama diri, tanpa artikel.",
  "2-0": "“Information” tak terhitung → little (“few” untuk kata benda terhitung).",
  "2-1": "“Ideas” terhitung dan kalimatnya positif → a few.",
  "2-2": "“Advice” tak terhitung — ukur dengan “a piece of advice”.",
  "2-3": "“Experience” (pengalaman/keahlian) tak terhitung → a lot of.",
  "2-4": "“Furniture” tak terhitung → some (many / a few butuh kata benda terhitung).",
  "2-5": "Kalimat negatif + “time” yang tak terhitung → much.",
  "2-6": "“Research” tak terhitung → a lot of (tidak pernah “many researches”).",
  "2-7": "“Evidence” tak terhitung: a lot of evidence, dengan kata kerja tunggal.",
  "3-0": "Interested in — kata sifat + in.",
  "3-1": "Concentrate / rely / depend / insist on.",
  "3-2": "Responsible for — seperti reason for, demand for.",
  "3-3": "Shout / yell / point at seseorang.",
  "3-4": "Prepare / apply / wait / hope for.",
  "3-5": "Capable of + -ing.",
  "3-6": "A rise / increase / decrease in sesuatu.",
  "3-7": "An impact / effect / influence on sesuatu.",
  "4-0": "Kata sifat panjang → more + kata sifat + than.",
  "4-1": "Kata sifat pendek → -er + than.",
  "4-2": "Jangan “more cheaper” — cheap itu pendek, cukup cheaper.",
  "4-3": "Komparatif yang diulang menunjukkan perubahan yang terus berlanjut.",
  "4-4": "Kata sifat panjang → more difficult than.",
  "4-5": "easy → easier; “more easier” menggandakan komparatif.",
  "4-6": "“Far” memperkuat komparatif: far more expensive.",
  "4-7": "Pola: The + komparatif…, the + komparatif…",
  "5-0": "“The number of” tunggal → has.",
  "5-1": "Subjeknya jamak, “crime rates” → are.",
  "5-2": "Dengan neither…nor, kata kerja mengikuti subjek terdekat: students → were.",
  "5-3": "Dua subjek dihubungkan “and” → kata kerja jamak.",
  "5-4": "“Every one of…” tunggal → is.",
  "5-5": "“Research” tak terhitung, kata kerjanya tunggal → has.",
  "5-6": "“Some of” + “information” yang tak terhitung → tunggal: is.",
  "5-7": "Mathematics terlihat jamak tetapi maknanya tunggal.",
  "6-0": "Dua aksi selesai secara berurutan → past simple + past simple.",
  "6-1": "Aksi latar yang sedang berlangsung (were hiking) dipotong past simple (hit).",
  "6-2": "Aksi yang lebih dulu memakai past perfect: had already left.",
  "6-3": "Durasi sebelum kejadian lampau → past perfect continuous, lalu past simple.",
  "6-4": "Urutan aksi cepat yang selesai → past simple.",
  "6-5": "Aksi sedang berlangsung (was cooking) dipotong aksi singkat (rang).",
  "6-6": "Menyelesaikan laporan terjadi lebih dulu → past perfect; lalu past simple “felt”.",
  "6-7": "Menunggunya berlanjut sampai bus tiba → had been waiting + arrived.",
  "7-0": "“Believe” kata kerja keadaan → present simple.",
  "7-1": "Durasi sampai sekarang (for the last six months) → present perfect continuous.",
  "7-2": "“Ever … before” (pengalaman sampai sekarang) → present perfect.",
  "7-3": "Aksi sementara yang sedang berlangsung (at the moment) → present continuous.",
  "7-4": "“Yet” menghubungkan lampau dengan sekarang → present perfect negatif.",
  "7-5": "Terjadi sekitar sekarang dan sifatnya sementara → am preparing.",
  "7-6": "Grafik menyatakan fakta → present simple: shows.",
  "7-7": "Dimulai di masa lalu dan masih berlangsung (for three months) → present perfect.",
  "8-0": "Sedang berlangsung di waktu depan (kehidupan tahun 2100) → future continuous.",
  "8-1": "Keadaan masa depan yang sederhana → won’t be.",
  "8-2": "Menggambarkan keadaan pada waktu itu → will be.",
  "8-3": "Aktivitas yang sedang berlangsung pada waktu itu → future continuous.",
  "8-4": "Selesai sebelum titik itu → future perfect.",
  "8-5": "Prediksi sederhana tentang perannya kelak → will likely serve.",
  "8-6": "Durasi sampai satu titik depan (for several years) → future perfect continuous.",
  "8-7": "Selesai pada 2065 → future perfect.",
  "9-0": "“At the moment” → pasif present continuous: are being reviewed.",
  "9-1": "“Yesterday” → pasif past simple: was submitted.",
  "9-2": "“Already”, masih relevan sekarang → pasif present perfect.",
  "9-3": "Rutinitas → pasif present simple: are inspected.",
  "9-4": "“Last year” → pasif past simple: were implemented.",
  "9-5": "Sedang berlangsung saat kunjungan lampau → pasif past continuous.",
  "9-6": "“Next week” → pasif future: will be approved.",
  "9-7": "Aktif present continuous → pasif present continuous: are being conducted.",
  "10-0": "Conditional tipe 2: If + past simple … would + kata kerja dasar.",
  "10-1": "Hasil conditional tipe 3 → would have + V3.",
  "10-2": "Situasi nyata dan mungkin → tipe 1: will / won’t.",
  "10-3": "Tidak nyata di masa kini dengan “be” → If I were.",
  "10-4": "Hasil conditional tipe 2 → would decrease.",
  "10-5": "Syarat lampau yang tidak nyata → would have + V3.",
  "10-6": "Kemungkinan nyata di masa depan → tipe 1: will reduce.",
  "10-7": "Conditional campuran: syarat lampau, hasil sekarang → would be … now.",
  "11-0": "Kemungkinan lampau yang tidak terjadi → could have + V3.",
  "11-1": "Yakin tentang masa lalu berdasar bukti → must have.",
  "11-2": "Yakin sesuatu mustahil terjadi di masa lalu → can’t have.",
  "11-3": "Penyesalan tentang masa lalu → should have + V3.",
  "11-4": "“Had better” menyiratkan akibat buruk jika saran diabaikan.",
  "11-5": "Keharusan yang kuat → must.",
  "11-6": "Kemungkinan yang tidak pasti → might.",
  "11-7": "“Can” tidak punya bentuk masa depan → will be able to.",
  "12-0": "Orang sebagai subjek → who (atau that).",
  "12-1": "Tempat → where.",
  "12-2": "Kepemilikan (strategi si pelatih) → whose.",
  "12-3": "Waktu → when.",
  "12-4": "Kepemilikan (ayah si pemain) → whose.",
  "12-5": "Benda → which (atau that).",
  "12-6": "Klausa defining tentang tim → that (atau which).",
  "12-7": "Klausa non-defining (dengan koma) memakai who — tidak pernah “that”.",
  "13-0": "Klausa alasan → because.",
  "13-1": "Klausa waktu → When.",
  "13-2": "Despite + frasa benda (although butuh klausa lengkap).",
  "13-3": "Tujuan → so that + klausa.",
  "13-4": "Kontras antara usaha dan hasil → Although.",
  "13-5": "Even though + klausa menunjukkan kontras.",
  "13-6": "Dua klausa independen butuh kata hubung — koma saja adalah comma splice.",
  "13-7": "Klausa “while” sendirian adalah fragmen — perlu klausa independen.",
};
