// Auto-extracted grammar content data (pure data, no logic).
export const TAG_ID = {
  1: "a / an / the / Ø (tanpa artikel)",
  2: "Kata benda terhitung, tak terhitung & kuantifier",
  3: "Preposisi pasangan & frasanya",
  4: "Perbandingan & superlatif",
  5: "Kesesuaian subjek–kata kerja",
  6: "Simple, continuous, perfect (lampau)",
  7: "Simple, continuous, perfect (kini)",
  8: "will, going to & bentuk perfect",
  9: "be + V3 di semua tense",
  10: "Tipe 1, 2, 3 & campuran",
  11: "Kemampuan, kemungkinan, keharusan",
  12: "who, which, that, whose…",
  13: "Klausa & kata hubung",
  14: "-ing vs to + verb (gerund vs infinitive)",
  15: "Kalimat tidak langsung: say, tell & backshift tense",
  16: "namun, oleh karena itu, meskipun…",
  17: "kata ganti & rujukan: it, they, this, one, such",
  18: "Menyusun frasa nomina yang lebih panjang",
  19: "Pertanyaan langsung, tidak langsung & question tag",
  20: "Koma, semicolon & daftar yang seimbang",
  21: "so/such, inversion, kausatif",
};

export const LEARN_ID = {
  1: [
    "Pakai a/an untuk benda tunggal terhitung yang belum spesifik atau baru pertama kali disebut.",
    "Pakai the untuk sesuatu yang spesifik, sudah disebut, satu-satunya, atau bentuk superlatif.",
    "Tanpa artikel (Ø) untuk kata benda jamak/tak terhitung bermakna umum dan kebanyakan nama diri.",
  ],
  2: [
    "Kata benda tak terhitung (information, advice, research…) tidak punya bentuk jamak, tidak memakai a/an, dan kata kerjanya tunggal; ukur dengan “a piece of…”.",
    "some untuk kalimat positif, tawaran, dan permintaan; any untuk kalimat negatif dan pertanyaan.",
    "many/a few untuk terhitung, much/a little untuk tak terhitung; a lot of bisa keduanya. few/little = hampir tidak ada; a few/a little = ada beberapa, cukup.",
  ],
  3: [
    "Banyak kata kerja punya preposisi pasangan tetap: depend on, wait for, deal with — hafalkan sebagai satu paket.",
    "Kata sifat juga punya pasangan: interested in, responsible for, capable of, satisfied with.",
    "Kata benda pun begitu: increase in, impact on, demand for, reason for.",
    "Kalau ragu, cek kamus kolokasi untuk melihat preposisi yang lazim mengikuti sebuah kata.",
  ],
  4: [
    "Komparatif: kata sifat pendek + -er, kata sifat panjang pakai more, lalu “than”; jangan digandakan (✗ more cheaper).",
    "Superlatif: the + -est / the most untuk tiga hal atau lebih; “the” hilang setelah kata milik (our best package).",
    "Perkuat dengan slightly/far/significantly + komparatif atau by far + superlatif; pola “the more…, the more…” menunjukkan perubahan.",
  ],
  5: [
    "Subjek tunggal → kata kerja tunggal; subjek jamak → jamak. Dengan or/nor, kata kerja mengikuti subjek terdekat.",
    "everyone/each/every → tunggal; few/many/several → jamak; some/all/none mengikuti kata benda setelahnya. “The number of” tunggal, “a number of” jamak.",
    "There is/are mengikuti subjek di belakangnya; judul, negara, jumlah uang, dan mata pelajaran seperti mathematics dihitung tunggal.",
  ],
  6: [
    "Past simple untuk aksi selesai dan urutan kejadian di masa lampau.",
    "used to/would untuk kebiasaan lampau; hanya used to yang bisa dipakai untuk keadaan (state).",
    "Past continuous untuk aksi yang sedang berlangsung di satu titik lampau, sering “dipotong” oleh past simple.",
    "Past perfect (had + V3) untuk kejadian yang lebih dulu dari kejadian lampau lain.",
    "Past perfect continuous menekankan durasi sampai satu titik di masa lampau.",
  ],
  7: [
    "Present simple untuk rutinitas, fakta umum, dan jadwal.",
    "Present continuous untuk situasi sementara, yang sedang terjadi, dan tren; kata kerja keadaan (know, want…) biasanya tidak memakai bentuk ini.",
    "Present perfect menghubungkan lampau dengan sekarang (for/since, ever, yet); kalau waktunya disebut jelas, pakai past simple.",
    "Present perfect continuous menekankan durasi/aktivitasnya; bentuk simple menekankan hasil atau jumlah.",
  ],
  8: [
    "will untuk keputusan spontan, janji, dan prediksi berdasar opini.",
    "going to untuk rencana yang sudah ada dan prediksi dari bukti; present continuous untuk janji temu pasti, present simple untuk jadwal.",
    "Future continuous (will be + V-ing) untuk aksi yang sedang berlangsung di satu waktu di masa depan.",
    "Future perfect (will have + V3) untuk yang selesai sebelum satu titik di masa depan (by / by the time).",
    "Future perfect continuous untuk durasi sampai satu titik di masa depan.",
  ],
  9: [
    "Bentuk pasif = be + V3, dan “be”-nya berubah mengikuti tense (is discussed, was discussed, has been discussed…).",
    "Pakai pasif saat objek lebih penting daripada pelaku, pelakunya tak diketahui, atau untuk nada akademik yang formal.",
  ],
  10: [
    "Tipe 1 (nyata & mungkin): If + present, will.",
    "Tipe 2 (tidak nyata sekarang): If + past simple, would; dengan “be” pakai were.",
    "Tipe 3 (tidak nyata di masa lampau): If + past perfect, would have + V3.",
    "Campuran: syarat lampau, hasil sekarang — If + past perfect, would + kata kerja dasar.",
  ],
  11: [
    "can/could untuk kemampuan; be able to saat “can” tidak bisa dipakai; may/might/could untuk kemungkinan yang tidak pasti.",
    "could/might have + V3 = kemungkinan lampau; must have = yakin terjadi; can’t have = yakin tidak terjadi.",
    "must/have to untuk keharusan (lampau: had to); should have + V3 untuk penyesalan; had better memberi peringatan.",
    "Modals mengatur kekuatan opini: “could lead to” terdengar lebih berimbang daripada “will lead to”.",
  ],
  12: [
    "Klausa defining memberi info penting, tanpa koma; who/which/that bisa dihilangkan kalau berperan sebagai objek.",
    "Klausa non-defining memberi info tambahan di antara koma; jangan pakai “that” dan jangan hilangkan kata gantinya.",
    "whose = kepemilikan, where = tempat, when = waktu.",
  ],
  13: [
    "Klausa independen bisa berdiri sendiri; klausa dependen tidak. Hindari comma splice dan kalimat fragmen.",
    "Sebab-akibat: because/since/as + klausa; because of/due to + kata benda; so menunjukkan akibat.",
    "Kontras: although/even though + klausa; despite/in spite of + kata benda.",
    "Tujuan: so that + klausa, in order to + kata kerja; klausa waktu: when, while, before, after, until, as soon as.",
    "Untuk band 7 tidak perlu kalimat super panjang — variasi yang akurat lebih penting.",
  ],
  14: [
    "Aksi -ing di awal kalimat berfungsi sebagai subjek tunggal, jadi verbnya tunggal: “Reading widely improves vocabulary.”",
    "Verb pertama menentukan bentuk berikutnya: sebagian minta gerund (enjoy, avoid, suggest…), sebagian minta infinitive (decide, agree, afford…); hindari ✗ ‘suggest to do’ dan ✗ ‘enjoy to do’.",
    "Setelah begin/start/like arti sama, tetapi stop, remember, forget, try, regret berubah arti antara gerund dan infinitive (stop smoking = berhenti; stop to smoke = berhenti sejenak untuk merokok).",
    "Setelah preposition selalu gerund (interested in doing, look forward to doing); infinitive of purpose ‘to + verb’ = in order to, sedangkan ‘for + -ing’ menyatakan fungsi sebuah benda.",
  ],
  15: [
    "Setelah reporting verb bentuk lampau, tense biasanya di-backshift satu langkah ke belakang (present→past, present perfect/past→past perfect, will→would, must→had to), tetapi fakta umum boleh tetap present.",
    "Pronoun, kata waktu, dan kata tempat ikut bergeser secara logis: today→that day, tomorrow→the following day, yesterday→the day before, here→there, this→that, now→then.",
    "'say' tidak langsung diikuti orang sedangkan 'tell' harus (told me); tiap reporting verb punya pola sendiri: advise/warn/ask/tell sb to do, suggest/recommend + -ing atau that-clause, admit/deny + -ing, promise/offer/refuse/agree + to.",
    "Pertanyaan tidak langsung memakai urutan kalimat biasa (subjek sebelum verb), if/whether untuk yes-no, tanpa tanda tanya; permintaan atau perintah memakai asked/told sb (not) to do.",
  ],
  16: [
    "Ada tiga keluarga penghubung: conjunction (menyambung dua klausa dalam satu kalimat), sentence adverbial (membuka kalimat baru lalu koma), dan preposition (diikuti noun atau bentuk -ing, bukan klausa penuh).",
    "Kelompokkan penghubung berdasarkan fungsinya: penambahan, kontras/konsesi, sebab, hasil, contoh, dan penegasan ulang.",
    "Beri koma setelah adverbial di awal kalimat, dan gunakan titik atau titik koma sebelum ‘however’ agar tidak terjadi comma splice.",
    "Satu penghubung untuk satu ide: jangan menumpuk (✗ But however,) dan jangan menaruh klausa penuh setelah preposition (✗ Despite it was raining).",
  ],
  17: [
    "Dalam tulisan formal, sebuah perusahaan atau lembaga dianggap tunggal sehingga memakai it/its (bukan they); kata benda uncountable memakai it, sedangkan kata benda jamak memakai they/them/their.",
    "Gunakan this/that/these/those untuk merujuk ke keseluruhan gagasan di kalimat sebelumnya, dan tambahkan kata benda ringkasan agar rujukannya jelas.",
    "Alat substitusi seperti one/ones, the former/the latter, such + noun, dan do so membantu menghindari pengulangan kata dan membuat tulisan lebih mengalir.",
    "Hindari it/they yang ambigu, bedakan there is/are (memperkenalkan hal baru) dari it is (mengomentari), dan ingat its (milik) berbeda dari it's (it is).",
  ],
  18: [
    "Frasa nomina dibangun dari determiner + (adverb) + adjective + head noun + prepositional phrase, dan informasi penting sering ada di prepositional phrase seperti “an increase in production”.",
    "Beberapa adjective berurutan mengikuti urutan tetap opinion → size → age → shape → colour → origin → material → purpose, dan koma hanya dipakai antar adjective yang setara (coordinate).",
    "Noun+noun compound seperti “government policy” padat dengan nomina pertama tetap singular, sementara “of” dipakai untuk kepemilikan atau hasil spesifik seperti “the results of the survey”.",
    "Nominalisation mengubah verb/adjective menjadi noun (“growth in”, “a reduction in”, “an improvement in”, “a tendency to”) agar tulisan lebih padat dan formal untuk IELTS.",
  ],
  19: [
    "Pertanyaan langsung memakai inversion (auxiliary sebelum subject); di simple present/past yang tidak punya auxiliary, tambahkan do/does/did + verba dasar.",
    "Indirect/embedded question memakai urutan statement (subject sebelum verba), tanpa do-support, dan pakai if/whether untuk pertanyaan yes-no.",
    "Question tag: statement positif → tag negatif dan sebaliknya; tag meniru auxiliary di kalimatnya, dengan bentuk khusus seperti ‘aren't I?’, ‘shall we?’, ‘will you?’, ‘isn't there?’.",
    "Pertanyaan subject (Who called you?) tanpa do-support; pertanyaan object (Who did you call?) memakai do-support.",
  ],
  20: [
    "Koma dipakai sebelum FANBOYS yang menggabungkan dua independent clause, setelah anak kalimat atau linking adverb di depan, dan untuk memisahkan item daftar; menyambung dua kalimat lengkap hanya dengan koma disebut comma splice dan itu salah.",
    "Semicolon menghubungkan dua independent clause yang erat kaitannya (dan dipakai sebelum 'however'), sedangkan colon memperkenalkan daftar atau penjelasan setelah klausa yang sudah lengkap.",
    "Tanda kecil berdampak besar: bedakan 'its' (kepemilikan) dan 'it's' (= it is), gunakan huruf kapital dengan benar, dan hindari tanda seru dalam tulisan akademik.",
    "Struktur paralel: item dalam daftar, perbandingan, dan paired connector (both…and, not only…but also, either…or, neither…nor) harus memakai bentuk gramatikal yang sama.",
  ],
  21: [
    "so dipakai sebelum adjective/adverb, sedangkan such sebelum kata benda (noun); keduanya sering diikuti klausa hasil that untuk memberi penekanan.",
    "Setelah negative adverbial (Not only, Rarely, Under no circumstances) atau pada conditional inversion (Had…, Were…, Should…), susunannya dibalik menjadi auxiliary + subject.",
    "Causative: have/get something done berarti menyuruh orang lain melakukannya, make/let + orang + bare infinitive, dan get + orang + to-infinitive; perhatikan bentuk participle-nya.",
    "Subjunctive memakai base verb setelah suggest/recommend/insist/demand + that dan setelah It is essential/vital that, tanpa -s dan tanpa auxiliary — dipakai dalam tulisan formal.",
  ],
};

export const EX_ID = {
  "1-0": "“The number of…” merujuk jumlah yang spesifik, jadi pakai “the” (dan kata kerja tunggal).",
  "1-1": "Baru pertama kali disebut, satu dari banyak lini produk → a.",
  "1-2": "Kata benda jamak yang bermakna umum tidak memakai artikel.",
  "1-3": "Superlatif selalu memakai “the”: the most popular.",
  "1-4": "Satu kenaikan yang belum spesifik, baru diperkenalkan → a.",
  "1-5": "Satu periode (tidak ditentukan yang mana) sepanjang itu → a three-year period.",
  "1-6": "“A significant decrease” baru pertama kali disebut → a.",
  "1-7": "Kebanyakan nama kota dan negara adalah nama diri, tanpa artikel.",
  "2-0": "“Information” tak terhitung → little (“few” untuk kata benda terhitung).",
  "2-1": "“Ideas” terhitung dan kalimatnya positif → a few.",
  "2-2": "“Advice” tak terhitung — ukur dengan “a piece of advice”.",
  "2-3": "“Experience” (pengalaman/keahlian) tak terhitung → a lot of.",
  "2-4": "“Furniture” tak terhitung → some (many / a few butuh kata benda terhitung).",
  "2-5": "Kalimat negatif + “time” yang tak terhitung → much.",
  "2-6": "“Research” tak terhitung → a lot of (tidak pernah “many researches”).",
  "2-7": "“Evidence” tak terhitung: a lot of evidence, dengan kata kerja tunggal.",
  "3-0": "Interested in — kata sifat + in.",
  "3-1": "Concentrate / rely / depend / insist on.",
  "3-2": "Responsible for — seperti reason for, demand for.",
  "3-3": "Shout / yell / point at seseorang.",
  "3-4": "Prepare / apply / wait / hope for.",
  "3-5": "Capable of + -ing.",
  "3-6": "A rise / increase / decrease in sesuatu.",
  "3-7": "An impact / effect / influence on sesuatu.",
  "4-0": "Kata sifat panjang → more + kata sifat + than.",
  "4-1": "Kata sifat pendek → -er + than.",
  "4-2": "Jangan “more cheaper” — cheap itu pendek, cukup cheaper.",
  "4-3": "Komparatif yang diulang menunjukkan perubahan yang terus berlanjut.",
  "4-4": "Kata sifat panjang → more difficult than.",
  "4-5": "easy → easier; “more easier” menggandakan komparatif.",
  "4-6": "“Far” memperkuat komparatif: far more expensive.",
  "4-7": "Pola: The + komparatif…, the + komparatif…",
  "5-0": "“The number of” tunggal → has.",
  "5-1": "Subjeknya jamak, “crime rates” → are.",
  "5-2": "Dengan neither…nor, kata kerja mengikuti subjek terdekat: students → were.",
  "5-3": "Dua subjek dihubungkan “and” → kata kerja jamak.",
  "5-4": "“Every one of…” tunggal → is.",
  "5-5": "“Research” tak terhitung, kata kerjanya tunggal → has.",
  "5-6": "“Some of” + “information” yang tak terhitung → tunggal: is.",
  "5-7": "Mathematics terlihat jamak tetapi maknanya tunggal.",
  "6-0": "Dua aksi selesai secara berurutan → past simple + past simple.",
  "6-1": "Aksi latar yang sedang berlangsung (were hiking) dipotong past simple (hit).",
  "6-2": "Aksi yang lebih dulu memakai past perfect: had already left.",
  "6-3": "Durasi sebelum kejadian lampau → past perfect continuous, lalu past simple.",
  "6-4": "Urutan aksi cepat yang selesai → past simple.",
  "6-5": "Aksi sedang berlangsung (was cooking) dipotong aksi singkat (rang).",
  "6-6": "Menyelesaikan laporan terjadi lebih dulu → past perfect; lalu past simple “felt”.",
  "6-7": "Menunggunya berlanjut sampai bus tiba → had been waiting + arrived.",
  "7-0": "“Believe” kata kerja keadaan → present simple.",
  "7-1": "Durasi sampai sekarang (for the last six months) → present perfect continuous.",
  "7-2": "“Ever … before” (pengalaman sampai sekarang) → present perfect.",
  "7-3": "Aksi sementara yang sedang berlangsung (at the moment) → present continuous.",
  "7-4": "“Yet” menghubungkan lampau dengan sekarang → present perfect negatif.",
  "7-5": "Terjadi sekitar sekarang dan sifatnya sementara → am preparing.",
  "7-6": "Grafik menyatakan fakta → present simple: shows.",
  "7-7": "Dimulai di masa lalu dan masih berlangsung (for three months) → present perfect.",
  "8-0": "Sedang berlangsung di waktu depan (kehidupan tahun 2100) → future continuous.",
  "8-1": "Keadaan masa depan yang sederhana → won’t be.",
  "8-2": "Menggambarkan keadaan pada waktu itu → will be.",
  "8-3": "Aktivitas yang sedang berlangsung pada waktu itu → future continuous.",
  "8-4": "Selesai sebelum titik itu → future perfect.",
  "8-5": "Prediksi sederhana tentang perannya kelak → will likely serve.",
  "8-6": "Durasi sampai satu titik depan (for several years) → future perfect continuous.",
  "8-7": "Selesai pada 2065 → future perfect.",
  "9-0": "“At the moment” → pasif present continuous: are being reviewed.",
  "9-1": "“Yesterday” → pasif past simple: was submitted.",
  "9-2": "“Already”, masih relevan sekarang → pasif present perfect.",
  "9-3": "Rutinitas → pasif present simple: are inspected.",
  "9-4": "“Last year” → pasif past simple: were implemented.",
  "9-5": "Sedang berlangsung saat kunjungan lampau → pasif past continuous.",
  "9-6": "“Next week” → pasif future: will be approved.",
  "9-7": "Aktif present continuous → pasif present continuous: are being conducted.",
  "10-0": "Conditional tipe 2: If + past simple … would + kata kerja dasar.",
  "10-1": "Hasil conditional tipe 3 → would have + V3.",
  "10-2": "Situasi nyata dan mungkin → tipe 1: will / won’t.",
  "10-3": "Tidak nyata di masa kini dengan “be” → If I were.",
  "10-4": "Hasil conditional tipe 2 → would decrease.",
  "10-5": "Syarat lampau yang tidak nyata → would have + V3.",
  "10-6": "Kemungkinan nyata di masa depan → tipe 1: will reduce.",
  "10-7": "Conditional campuran: syarat lampau, hasil sekarang → would be … now.",
  "11-0": "Kemungkinan lampau yang tidak terjadi → could have + V3.",
  "11-1": "Yakin tentang masa lalu berdasar bukti → must have.",
  "11-2": "Yakin sesuatu mustahil terjadi di masa lalu → can’t have.",
  "11-3": "Penyesalan tentang masa lalu → should have + V3.",
  "11-4": "“Had better” menyiratkan akibat buruk jika saran diabaikan.",
  "11-5": "Keharusan yang kuat → must.",
  "11-6": "Kemungkinan yang tidak pasti → might.",
  "11-7": "“Can” tidak punya bentuk masa depan → will be able to.",
  "12-0": "Orang sebagai subjek → who (atau that).",
  "12-1": "Tempat → where.",
  "12-2": "Kepemilikan (strategi si pelatih) → whose.",
  "12-3": "Waktu → when.",
  "12-4": "Kepemilikan (ayah si pemain) → whose.",
  "12-5": "Benda → which (atau that).",
  "12-6": "Klausa defining tentang tim → that (atau which).",
  "12-7": "Klausa non-defining (dengan koma) memakai who — tidak pernah “that”.",
  "13-0": "Klausa alasan → because.",
  "13-1": "Klausa waktu → When.",
  "13-2": "Despite + frasa benda (although butuh klausa lengkap).",
  "13-3": "Tujuan → so that + klausa.",
  "13-4": "Kontras antara usaha dan hasil → Although.",
  "13-5": "Even though + klausa menunjukkan kontras.",
  "13-6": "Dua klausa independen butuh kata hubung — koma saja adalah comma splice.",
  "13-7": "Klausa “while” sendirian adalah fragmen — perlu klausa independen.",
  "14-0": "‘Recommend’ diikuti gerund → recommend increasing (bukan ‘recommend to increase’).",
  "14-1": "‘Decide’ diikuti infinitive → decide to postpone; ‘deciding postponing’ salah.",
  "14-2": "Aksi -ing sebagai subjek = gerund dan pakai verb tunggal ‘strengthens’; infinitive tidak dipakai sebagai subjek biasa.",
  "14-3": "Setelah preposition ‘in’ wajib gerund → interested in understanding.",
  "14-4": "Stop + gerund = aksi berhenti (ekspor berhenti tumbuh). Stop + to-infinitive berarti ‘berhenti sejenak untuk tumbuh’ — tidak masuk akal di sini.",
  "14-5": "Pada ‘look forward to’, kata ‘to’ adalah preposition, jadi diikuti gerund → look forward to presenting (bukan ‘to present’).",
  "14-6": "Remember + to-infinitive = tugas yang belum dikerjakan; remember + gerund = kenangan masa lalu, tidak cocok untuk sebuah instruksi.",
  "14-7": "Ini infinitive of purpose (= in order to reduce). ‘For + -ing’ menyatakan fungsi benda, bukan tujuan sebuah tindakan atau kebijakan.",
  "15-0": "Setelah reporting verb lampau (said), present 'are' backshift menjadi past 'were'.",
  "15-1": "'tell' langsung diikuti orang: told the students (bukan 'said the students' atau 'told to the students').",
  "15-2": "Present perfect 'have risen' backshift menjadi past perfect 'had risen'.",
  "15-3": "Modal 'will' berubah menjadi 'would' dalam reported speech.",
  "15-4": "Reported question memakai urutan kalimat biasa: 'where she had worked', bukan 'where had she worked' atau 'where did she work'.",
  "15-5": "Pertanyaan yes-no dilaporkan dengan 'if' atau 'whether', bukan 'that' atau 'what'.",
  "15-6": "Fakta ilmiah yang masih benar boleh tetap present simple (orbits); past perfect 'had orbited' salah di sini.",
  "15-7": "'recommend' (dan 'suggest') diikuti bentuk -ing atau that-clause, tidak pernah to + infinitive.",
  "16-0": "Diikuti frasa benda (‘the sharp rise…’), jadi pakai preposition ‘despite’. ‘Although’ butuh klausa lengkap, ‘however’ mengawali kalimat baru, dan ‘because’ menyatakan sebab, bukan konsesi.",
  "16-1": "Kalimat baru yang menyatakan hasil memakai adverbial ‘Therefore,’ + koma. ‘However’ untuk kontras, ‘because of’ butuh noun, dan ‘in addition’ untuk penambahan, bukan hasil.",
  "16-2": "‘because of’ adalah preposition dan diikuti noun (‘the heavy fog’). ‘because’ harus diikuti klausa lengkap dengan kata kerjanya sendiri.",
  "16-3": "Diikuti klausa lengkap (‘the government invested…’), jadi pakai conjunction ‘although’. ‘Despite’/‘because of’ butuh noun, dan ‘however’ tak bisa menyambung dua klausa dalam satu kalimat.",
  "16-4": "‘however’ adalah adverbial, bukan conjunction, jadi tak bisa menyambung dua klausa hanya dengan koma (comma splice). Pakai titik koma (atau titik) sebelum ‘however’.",
  "16-5": "‘Although’ + klausa lengkap itu benar. Jangan menumpuk penghubung (‘But however’) dan jangan menaruh klausa penuh setelah preposition (‘despite’/‘because of’).",
  "16-6": "‘for example’ memperkenalkan contoh dari ide sebelumnya. ‘in contrast’/‘nevertheless’ menyatakan kontras, ‘therefore’ menyatakan hasil.",
  "16-7": "Kalimat kedua bertentangan dengan yang pertama, jadi pakai adverbial konsesi ‘Nevertheless’. ‘Consequently’/‘Therefore’ menyatakan hasil, ‘Furthermore’ penambahan.",
  "17-0": "Dalam bahasa formal, sebuah perusahaan bersifat tunggal sehingga memakai 'its'; 'it's' berarti 'it is' dan 'their' menganggapnya jamak.",
  "17-1": "'Research' adalah kata benda uncountable, jadi memakai kata ganti tunggal 'it', bukan 'they' atau 'them'.",
  "17-2": "'This' + kata benda ringkasan ('increase') merujuk ke seluruh gagasan kalimat sebelumnya; 'These' butuh kata benda jamak.",
  "17-3": "'Machines' bersifat jamak dan countable sehingga penggantinya 'ones'; 'one' hanya untuk satu mesin.",
  "17-4": "'The former' = hal pertama (wind), 'the latter' = hal kedua (solar); 'the later' berkaitan dengan waktu, bukan urutan.",
  "17-5": "Pakai 'such + a + adjective + noun + that' untuk menunjukkan akibat; 'so' harus langsung sebelum kata sifat saja.",
  "17-6": "'Do so' adalah cara formal menggantikan seluruh tindakan yang sudah disebut ('lower its prices'); bentuk lain tidak gramatikal.",
  "17-7": "Gunakan 'there + are' untuk memperkenalkan subjek jamak baru ('countries'); 'there is' salah karena jamak, dan 'it are' tidak ada dalam bahasa Inggris.",
  "18-0": "Urutan adjective: opinion → size → age → shape → colour → origin → material → purpose. Opinion (beautiful) mendahului size (small), dan material (wooden) paling akhir: “a beautiful small wooden box”.",
  "18-1": "Kenaikan jumlah memakai “increase in”, bukan “increase of”. “Increase of” hanya dipakai untuk angka pasti, misalnya “an increase of 5%”, sedangkan “increase on” salah.",
  "18-2": "Dua nomina digabung, nomina pertama berperan seperti adjective dan tetap singular: “traffic congestion”. Versi dengan “of” atau “’s” terdengar tidak alami di sini.",
  "18-3": "Untuk hasil yang spesifik kita pakai “of”: “the results of the survey”. Membaliknya menjadi “the survey of the results” mengubah makna sehingga menjadi salah.",
  "18-4": "Urutan adjective: age → origin → material. “ancient” (age) → “Greek” (origin) → “stone” (material): “an ancient Greek stone statue”.",
  "18-5": "Kenaikan digambarkan dengan “a growth in” + noun: “a growth in the number of students”. Preposisinya “in”, bukan “of”, dan pakai noun “growth”, bukan bentuk -ing.",
  "18-6": "Polanya “a tendency to” + kata kerja dasar: “a tendency to overspend”. Bukan “tendency of” atau “tendency for” bila diikuti verb.",
  "18-7": "Versi formal memakai nominalisation: “reduce” → “a reduction in”, “improve” → “an improvement in”. Dua klausa menjadi frasa nomina yang padat, dan keduanya memakai “in”.",
  "19-0": "Subject ‘the two graphs’ jamak dan ‘show’ verba utama, jadi simple present butuh do-support: ‘Do … show?’. ‘Does’ salah agreement, ‘Are’ salah auxiliary.",
  "19-1": "Di dalam embedded question, urutan tetap statement tanpa do-support: ‘why the figures fell’, bukan bentuk inversion ‘did the figures fall’.",
  "19-2": "Embedded question tipe yes-no disambung dengan if atau whether: ‘asked whether I had…’. ‘that’ dan ‘what’ tidak cocok untuk pertanyaan yes/no di sini.",
  "19-3": "Statement present simple ‘illustrates’ memakai auxiliary ‘do’, jadi tag-nya ‘doesn't it?’. ‘isn't it’ salah karena verbanya bukan ‘be’.",
  "19-4": "Tag khusus untuk statement positif ‘I'm …’ adalah ‘aren't I?’ — bentuk baku; ‘amn't I’ bukan bahasa Inggris standar.",
  "19-5": "‘Which country’ adalah subject dari pertanyaan, jadi tanpa do-support: ‘Which country had…?’, bukan ‘did have’.",
  "19-6": "Statement present perfect ‘You've seen’ memakai auxiliary ‘have’, jadi tag meniru auxiliary itu: ‘haven't you?’.",
  "19-7": "Pola ‘There is …’ memakai tag ‘isn't there?’ — kata ‘there’ tetap dipertahankan di dalam tag.",
  "20-0": "Dua independent clause tidak boleh disambung hanya dengan koma (comma splice); pakai semicolon, titik, atau koma + FANBOYS.",
  "20-1": "Anak kalimat di depan ('Although…') diikuti koma, dan tidak ada koma setelah kata penghubungnya.",
  "20-2": "Saat FANBOYS menyambung dua klausa lengkap, komanya diletakkan sebelum konjungsi, bukan sesudahnya.",
  "20-3": "'However' adalah linking adverb, bukan konjungsi; pakai semicolon sebelumnya dan koma sesudahnya — koma saja menghasilkan comma splice.",
  "20-4": "Colon memperkenalkan daftar hanya setelah klausa yang sudah lengkap; 'The report examines three factors' sudah lengkap.",
  "20-5": "'It's' = it is / it has; 'its' (tanpa apostrof) menunjukkan kepemilikan. Di sini 'it's cheap' berarti 'it is cheap'.",
  "20-6": "Item daftar harus sebentuk: agar sejajar dengan gerund 'reading' dan 'writing', pakai 'listening'.",
  "20-7": "'Not only … but also' menyambung bentuk yang sama; pasangkan adjective 'cheap' dengan adjective 'time-saving', bukan dengan klausa.",
  "21-0": "Sebelum adjective (steady) pakai ‘so … that’ untuk menyatakan akibat. ‘such’ butuh kata benda, sedangkan ‘very/too’ tidak bisa diikuti klausa hasil that.",
  "21-1": "‘a striking gap’ adalah frasa kata benda, jadi pakai ‘such a … that’. ‘so’ hanya cocok langsung sebelum kata sifat, bukan sebelum ‘a’.",
  "21-2": "Negative adverbial ‘Under no circumstances’ di depan memaksa inversion: auxiliary + subject → ‘should the raw data’. Jangan menambahkan ‘not’ kedua.",
  "21-3": "‘Rarely’ di awal memicu inversion: auxiliary + subject + verb → ‘do scientists find’. Tanpa auxiliary kalimatnya salah.",
  "21-4": "Ini gagasan third conditional (masa lampau, tidak nyata). Inversion ‘Had’ menggantikan ‘If … had’. ‘Should’ menandakan kemungkinan masa depan, bukan masa lampau.",
  "21-5": "‘have something done’ memakai past participle: ‘had the calculations checked’. Subjek mengatur jasanya, orang lain yang mengerjakan.",
  "21-6": "Setelah ‘insist that’, subjunctive memakai base verb untuk semua subjek, tanpa -s: ‘that each candidate complete…’.",
  "21-7": "Setelah ‘Not only’ di depan, balik auxiliary dan subject: ‘Not only was he late…’. Membiarkan ‘he was’ tanpa inversion adalah kesalahan umum band-6.",
};
