// Grammar reference data (pure data). A "look it up" companion to the drills.
export const REFERENCE = {
  // Common irregular verbs: [base, past simple, past participle]
  irregulars: [
    ["be", "was / were", "been"], ["become", "became", "become"], ["begin", "began", "begun"],
    ["break", "broke", "broken"], ["bring", "brought", "brought"], ["build", "built", "built"],
    ["buy", "bought", "bought"], ["catch", "caught", "caught"], ["choose", "chose", "chosen"],
    ["come", "came", "come"], ["cost", "cost", "cost"], ["cut", "cut", "cut"],
    ["do", "did", "done"], ["draw", "drew", "drawn"], ["drink", "drank", "drunk"],
    ["drive", "drove", "driven"], ["eat", "ate", "eaten"], ["fall", "fell", "fallen"],
    ["feel", "felt", "felt"], ["find", "found", "found"], ["fly", "flew", "flown"],
    ["forget", "forgot", "forgotten"], ["get", "got", "got / gotten"], ["give", "gave", "given"],
    ["go", "went", "gone"], ["grow", "grew", "grown"], ["have", "had", "had"],
    ["hear", "heard", "heard"], ["hold", "held", "held"], ["keep", "kept", "kept"],
    ["know", "knew", "known"], ["lead", "led", "led"], ["leave", "left", "left"],
    ["lend", "lent", "lent"], ["lose", "lost", "lost"], ["make", "made", "made"],
    ["mean", "meant", "meant"], ["meet", "met", "met"], ["pay", "paid", "paid"],
    ["put", "put", "put"], ["read", "read", "read"], ["ride", "rode", "ridden"],
    ["rise", "rose", "risen"], ["run", "ran", "run"], ["say", "said", "said"],
    ["see", "saw", "seen"], ["sell", "sold", "sold"], ["send", "sent", "sent"],
    ["set", "set", "set"], ["show", "showed", "shown"], ["sing", "sang", "sung"],
    ["sit", "sat", "sat"], ["sleep", "slept", "slept"], ["speak", "spoke", "spoken"],
    ["spend", "spent", "spent"], ["stand", "stood", "stood"], ["swim", "swam", "swum"],
    ["take", "took", "taken"], ["teach", "taught", "taught"], ["tell", "told", "told"],
    ["think", "thought", "thought"], ["throw", "threw", "thrown"], ["understand", "understood", "understood"],
    ["wear", "wore", "worn"], ["win", "won", "won"], ["write", "wrote", "written"],
  ],
  // 12 tenses: { name, form, use, useId, ex }
  tenses: [
    { name: "Present Simple", form: "subject + verb (+s)", use: "Habits, facts, timetables.", useId: "Kebiasaan, fakta, jadwal.", ex: "Water boils at 100°C." },
    { name: "Present Continuous", form: "am/is/are + verb-ing", use: "Happening now or temporary.", useId: "Sedang terjadi atau sementara.", ex: "Prices are rising sharply." },
    { name: "Present Perfect", form: "have/has + past participle", use: "Past action with present relevance; experience.", useId: "Tindakan lampau yang relevan kini; pengalaman.", ex: "The committee has approved the plan." },
    { name: "Present Perfect Continuous", form: "have/has been + verb-ing", use: "Duration continuing up to now.", useId: "Durasi yang berlanjut hingga kini.", ex: "She has been studying for three hours." },
    { name: "Past Simple", form: "verb-ed / irregular V2", use: "A finished action at a known past time.", useId: "Tindakan selesai pada waktu lampau tertentu.", ex: "They launched the survey last year." },
    { name: "Past Continuous", form: "was/were + verb-ing", use: "In progress in the past; interrupted action.", useId: "Sedang berlangsung di masa lampau; terinterupsi.", ex: "I was reading when the alarm rang." },
    { name: "Past Perfect", form: "had + past participle", use: "An action before another past action.", useId: "Tindakan sebelum tindakan lampau lain.", ex: "The train had left before we arrived." },
    { name: "Past Perfect Continuous", form: "had been + verb-ing", use: "Duration up to a point in the past.", useId: "Durasi hingga suatu titik di masa lampau.", ex: "He had been working there for a decade." },
    { name: "Future Simple", form: "will + verb", use: "Predictions, instant decisions, promises.", useId: "Prediksi, keputusan spontan, janji.", ex: "The results will be published soon." },
    { name: "Future Continuous", form: "will be + verb-ing", use: "In progress at a future moment.", useId: "Sedang berlangsung pada saat di masa depan.", ex: "This time tomorrow I will be travelling." },
    { name: "Future Perfect", form: "will have + past participle", use: "Completed by a future point.", useId: "Selesai sebelum suatu titik di masa depan.", ex: "By 2030 they will have finished the bridge." },
    { name: "Future Perfect Continuous", form: "will have been + verb-ing", use: "Duration by a future point.", useId: "Durasi hingga suatu titik di masa depan.", ex: "By June she will have been living here for a year." },
  ],
  // Dependent prepositions: { phrase, ex }
  prepositions: [
    { phrase: "depend on", ex: "Outcomes depend on funding." },
    { phrase: "rely on", ex: "They rely on public transport." },
    { phrase: "insist on", ex: "She insisted on a review." },
    { phrase: "concentrate on", ex: "Concentrate on the evidence." },
    { phrase: "afraid of", ex: "He is afraid of failure." },
    { phrase: "aware of", ex: "Be aware of the risks." },
    { phrase: "capable of", ex: "The system is capable of scaling." },
    { phrase: "proud of", ex: "They are proud of the results." },
    { phrase: "consist of", ex: "The course consists of six modules." },
    { phrase: "accuse (sb) of", ex: "He was accused of negligence." },
    { phrase: "good at", ex: "She is good at analysis." },
    { phrase: "responsible for", ex: "Parents are responsible for supervision." },
    { phrase: "famous for", ex: "The city is famous for its heritage." },
    { phrase: "suitable for", ex: "The plan is suitable for rural areas." },
    { phrase: "apologise for", ex: "They apologised for the delay." },
    { phrase: "interested in", ex: "Students are interested in the topic." },
    { phrase: "involved in", ex: "He was involved in the project." },
    { phrase: "an increase in", ex: "There was an increase in demand." },
    { phrase: "succeed in", ex: "They succeeded in reducing waste." },
    { phrase: "participate in", ex: "Citizens participate in decisions." },
    { phrase: "believe in", ex: "She believes in reform." },
    { phrase: "similar to", ex: "The trend is similar to last year's." },
    { phrase: "related to", ex: "The issue is related to policy." },
    { phrase: "according to", ex: "According to the report, costs fell." },
    { phrase: "object to", ex: "Residents objected to the plan." },
    { phrase: "prefer (sth) to", ex: "They prefer cycling to driving." },
    { phrase: "associated with", ex: "Risks associated with pollution." },
    { phrase: "deal with", ex: "The agency deals with complaints." },
    { phrase: "cope with", ex: "Hospitals cope with demand." },
    { phrase: "satisfied with", ex: "Users are satisfied with the service." },
    { phrase: "familiar with", ex: "Be familiar with the rules." },
    { phrase: "comply with", ex: "Firms must comply with regulations." },
    { phrase: "contribute to", ex: "Emissions contribute to warming." },
    { phrase: "result in", ex: "The delay resulted in losses." },
    { phrase: "benefit from", ex: "Regions benefit from investment." },
    { phrase: "focus on", ex: "The study focuses on teenagers." },
  ],
  // Linking words grouped by function
  linkers: [
    { fn: "Addition", fnId: "Penambahan", words: ["moreover", "furthermore", "in addition", "additionally", "besides", "what is more"] },
    { fn: "Contrast", fnId: "Kontras", words: ["however", "nevertheless", "nonetheless", "on the other hand", "whereas", "in contrast", "conversely"] },
    { fn: "Cause", fnId: "Sebab", words: ["because", "since", "as", "due to", "owing to"] },
    { fn: "Result", fnId: "Akibat", words: ["therefore", "consequently", "thus", "as a result", "hence", "thereby"] },
    { fn: "Example", fnId: "Contoh", words: ["for instance", "for example", "such as", "namely", "to illustrate"] },
    { fn: "Conclusion", fnId: "Simpulan", words: ["in conclusion", "to sum up", "overall", "in summary", "on balance"] },
  ],
  // Glossary of grammar terms: { term, def, defId }
  glossary: [
    { term: "Clause", def: "A group of words with a subject and a verb.", defId: "Sekelompok kata yang punya subjek dan kata kerja." },
    { term: "Phrase", def: "A group of words without a subject–verb pair.", defId: "Sekelompok kata tanpa pasangan subjek–kata kerja." },
    { term: "Subject", def: "The person or thing that does the action.", defId: "Orang atau benda yang melakukan tindakan." },
    { term: "Object", def: "The person or thing that receives the action.", defId: "Orang atau benda yang menerima tindakan." },
    { term: "Auxiliary verb", def: "A helping verb (be, do, have) used to form tenses and questions.", defId: "Kata kerja bantu (be, do, have) untuk membentuk tense dan pertanyaan." },
    { term: "Modal verb", def: "A verb like can, must, should that shows possibility, obligation or ability.", defId: "Kata kerja seperti can, must, should yang menunjukkan kemungkinan, kewajiban, atau kemampuan." },
    { term: "Participle", def: "A verb form used in tenses or as an adjective (-ing / past participle).", defId: "Bentuk kata kerja untuk tense atau sebagai kata sifat (-ing / past participle)." },
    { term: "Gerund", def: "The -ing form of a verb used as a noun.", defId: "Bentuk -ing dari kata kerja yang dipakai sebagai kata benda." },
    { term: "Infinitive", def: "The base form of a verb, usually with 'to'.", defId: "Bentuk dasar kata kerja, biasanya dengan 'to'." },
    { term: "Article", def: "a, an or the, placed before a noun.", defId: "a, an, atau the yang diletakkan sebelum kata benda." },
    { term: "Determiner", def: "A word before a noun that shows which/how many (the, this, some, many).", defId: "Kata sebelum benda yang menunjukkan yang mana/berapa (the, this, some, many)." },
    { term: "Quantifier", def: "A determiner showing quantity (much, many, few, some).", defId: "Determiner yang menunjukkan jumlah (much, many, few, some)." },
    { term: "Antecedent", def: "The noun that a pronoun refers back to.", defId: "Kata benda yang dirujuk oleh sebuah kata ganti." },
    { term: "Relative clause", def: "A clause that describes a noun, starting with who/which/that.", defId: "Klausa yang menjelaskan kata benda, diawali who/which/that." },
    { term: "Subordinate clause", def: "A clause that cannot stand alone; it depends on a main clause.", defId: "Klausa yang tak bisa berdiri sendiri; bergantung pada klausa utama." },
    { term: "Independent clause", def: "A clause that can stand alone as a sentence.", defId: "Klausa yang bisa berdiri sendiri sebagai kalimat." },
    { term: "Conjunction", def: "A joining word (and, but, because, although).", defId: "Kata penghubung (and, but, because, although)." },
    { term: "Preposition", def: "A word showing relationship (in, on, at, of, for).", defId: "Kata yang menunjukkan hubungan (in, on, at, of, for)." },
    { term: "Collocation", def: "Words that naturally go together (make a decision, heavy rain).", defId: "Kata-kata yang lazim dipasangkan (make a decision, heavy rain)." },
    { term: "Countable noun", def: "A noun you can count and make plural (book → books).", defId: "Kata benda yang bisa dihitung dan dijamakkan (book → books)." },
    { term: "Uncountable noun", def: "A noun with no plural form (information, advice).", defId: "Kata benda tanpa bentuk jamak (information, advice)." },
    { term: "Comparative", def: "The -er/more form comparing two things (bigger, more useful).", defId: "Bentuk -er/more yang membandingkan dua hal (bigger, more useful)." },
    { term: "Superlative", def: "The -est/most form for the extreme of a group (the biggest).", defId: "Bentuk -est/most untuk yang paling dalam kelompok (the biggest)." },
    { term: "Passive voice", def: "When the subject receives the action (be + past participle).", defId: "Ketika subjek menerima tindakan (be + past participle)." },
    { term: "Active voice", def: "When the subject does the action.", defId: "Ketika subjek melakukan tindakan." },
    { term: "Tense", def: "The verb form showing time (past, present, future).", defId: "Bentuk kata kerja yang menunjukkan waktu (lampau, kini, depan)." },
    { term: "Aspect", def: "Whether an action is simple, continuous or perfect.", defId: "Apakah tindakan bersifat simple, continuous, atau perfect." },
    { term: "Cohesion", def: "How ideas link smoothly using reference and linking words.", defId: "Bagaimana ide terhubung mulus lewat rujukan dan kata penghubung." },
    { term: "Register", def: "How formal or informal the language is.", defId: "Seberapa formal atau informal bahasanya." },
  ],
};
