// Generate the per-theme vocabulary chunks and the lightweight manifest from
// the canonical src/content/vocab.js. Re-run after editing vocab.js:
//   node scripts/split-vocab.mjs
//
// Output:
//   src/content/vocab/manifest.js  — export const INDEX = [{w, theme}, ...]  (small; drives
//                                     stats, browse chips and study-queue selection)
//   src/content/vocab/t/<theme>.js — export default [ {full entry}, ... ]     (loaded on demand)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(root, "src/content/vocab.js");
const OUTDIR = path.join(root, "src/content/vocab");
const TDIR = path.join(OUTDIR, "t");

const src = fs.readFileSync(SRC, "utf8");
const { VOCAB } = new Function(src.replace(/export const/g, "const") + ";return {VOCAB};")();

// group by theme, alphabetical within each theme
const byTheme = {};
for (const e of VOCAB) (byTheme[e.theme] ||= []).push(e);
for (const t of Object.keys(byTheme)) byTheme[t].sort((a, b) => a.w.toLowerCase().localeCompare(b.w.toLowerCase()));

// clean the theme dir of stale files
fs.mkdirSync(TDIR, { recursive: true });
for (const f of fs.readdirSync(TDIR)) if (f.endsWith(".js")) fs.unlinkSync(path.join(TDIR, f));

// theme filenames must be safe: our theme keys are already [a-z0-9_]
for (const [theme, entries] of Object.entries(byTheme)) {
  const body = "// Auto-generated by scripts/split-vocab.mjs — do not edit by hand.\n"
    + "export default " + JSON.stringify(entries) + ";\n";
  fs.writeFileSync(path.join(TDIR, `${theme}.js`), body);
}

// manifest: global-alphabetical [{w, theme}]
const index = VOCAB.map(e => ({ w: e.w, theme: e.theme }))
  .sort((a, b) => a.w.toLowerCase().localeCompare(b.w.toLowerCase()));
const manifest = "// Auto-generated by scripts/split-vocab.mjs — do not edit by hand.\n"
  + "// Lightweight index (headword + theme) for stats, browse chips and study-queue selection.\n"
  + "export const INDEX = " + JSON.stringify(index) + ";\n";
fs.writeFileSync(path.join(OUTDIR, "manifest.js"), manifest);

console.log(`wrote ${Object.keys(byTheme).length} theme chunks + manifest (${VOCAB.length} words)`);
